### ISSUE TITLE
<MainHeader.SidebarToggle /> is undefined in the npm package

### ISSUE THREAD

**Issue by Em-Ant** [jonmpqts/reactjs-admin-lte#18]
You probably need to update the package, this component is not exported in the transpiled code of the npm package. Only the logo component is exported along with the MainHeader default.  

form `lib/MainHeader.js`
```js
...

MainHeader.propTypes = propTypes;

MainHeader.Logo = _MainHeaderLogo2.default;

exports.default = MainHeader;

```

**Comment by laurianek** [comment]
Having the same problem

**Comment by jonmpqts** [comment]
Sorry about the holdup. New version 0.4.0 pushed to npm that should have this exposed.
